Repository citation-style-language/schema, pull requests merged in 2020-06, with the labels that each got.

#221 Remove names.et-al.legacy-attributes pattern
  schemas/styles/csl.rnc
Labels: 1.1, deprecates

#222 Remove deprecated attribute values
  schemas/styles/csl.rnc
Labels: 1.1, deprecates

#225 Update csl-citation.json
  schemas/input/csl-citation.json
Labels: 1.0.2

#227 bwiernik new variables
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
Labels: 1.0.2

#224 Add issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#205 Add contributing.md
  contributing.md
Labels: documentation

#229 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: chore

#234 Add translated-title
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
Labels: 1.0.2, variables

#235 Add curator variable
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
Labels: 1.0.2, enhancement, variables

#231 Add international identifiers
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
Labels: 1.0.2

#233 CI: Add csl-citation.json test
  tests/schemas/input/test_json.py
Labels: chore, tests

#203 Split title -> Title-main/title-sub
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
  schemas/styles/csl.rnc
Labels: 1.1

#247 CI: Add a check for schema formatting
  .github/workflows/test.yaml
Labels: chore, tests

#248 Add pre-commit config hook
  .pre-commit-config.yaml
  CONTRIBUTING.md
  hooks/rnc-format-validate.py
Labels: chore

#252 Deprecate sentence case
  schemas/styles/csl.rnc
Labels: deprecates

#264 CI: refactor
  .github/workflows/test.yaml
Labels: chore

#262 tools: Merge rnc formatting/validations scripts
  .pre-commit-config.yaml
  hooks/rnc-format-validate.py
  tools/rnc-validate-format.py
Labels: chore, tools

#260 Add new cs:condition element to choose
  schemas/styles/csl-choose.rnc
  schemas/styles/csl.rnc
Labels: 1.1

#269 add reviewed-genre variable
  schemas/input/csl-data.json
  schemas/styles/csl-variables.rnc
Labels: 1.0.2

#271 Add sub/main form values to cs:text
  schemas/styles/csl-variables.rnc
  schemas/styles/csl.rnc
Labels: 1.1, enhancement

#265 tools: Fix rnc pre-commit
  .pre-commit-config.yaml
  tools/rnc-validate-format.py
Labels: bug, chore

#284 (input): Add EDTF as an option for date representation
  schemas/input/csl-data.json
Labels: 1.1, input

#292 add locator term sub-verbo, remove legacy workaround
  schemas/styles/csl-choose.rnc
  schemas/styles/csl-terms.rnc
Labels: 1.1
