Repository citation-style-language/schema, pull requests merged in 2020-05, with the labels that each got.

#183 adding variables for 1.0.x minor release
  csl-variables.rnc
Labels: variables

#184 adding new item types for 1.0.x minor release
  csl-types.rnc
Labels: itemtypes

#201 Add additional locator variables
  csl-citation.json
  csl-terms.rnc
Labels: 1.0.2

#194 More new types for 1.0.x minor release
  csl-data.json
  csl-types.rnc
Labels: itemtypes

#207 add document type
  csl-data.json
  csl-types.rnc
Labels: 1.0.2
